FROM mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:20231011.v1 as node_install
ENV NVM_VERSION 0.39.5
ENV NODE_VERSION 18.17.0
ENV NVM_DIR /usr/local/nvm
RUN mkdir $NVM_DIR
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v$NVM_VERSION/install.sh| bash
ENV NODE_PATH $NVM_DIR/v$NODE_VERSION/lib/node_modules
ENV PATH $NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH
RUN npm install -g npm@10.2.1 \
    && npm install yarn gulp-cli -g

FROM mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:20231011.v1
COPY --from=node_install /usr/local/nvm /usr/local/nvm
ENV NVM_VERSION 0.39.5
ENV NODE_VERSION 18.17.0
ENV NVM_DIR /usr/local/nvm
ENV NODE_PATH $NVM_DIR/v$NODE_VERSION/lib/node_modules
ENV PATH $NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH
RUN npm install --save-dev prettier eslint typescript-language-server unified-language-server typescript -g 

WORKDIR /src

COPY .bashrc.node /root/.bashrc.node
COPY .bashrc.node /root/.bashrc
COPY dev.env /root/dev.env

RUN git config --global user.email "bazhou@microsoft.com" \
    && git config --global user.name "Bartuer Zhou" \
    && git config --global --add safe.directory /root/etc/el