(defun bartuer-elisp-load ()
  "added when edit elisp file"
  (interactive)
  (turn-on-eldoc-mode)
  (flyspell-prog-mode)
  (paredit-mode t)
  (define-key paredit-mode-map "\M-(" 'paredit-wrap-round)
  (define-key paredit-mode-map "\M-)" 'paredit-splice-sexp)
  (define-key paredit-mode-map "\M-J" 'paredit-join-sexps)
  (define-key paredit-mode-map "\M-S" 'paredit-split-sexp)
  (define-key emacs-lisp-mode-map "\C-c\C-i" (lambda ()
                                               (interactive)
                                               (insert "(interactive)")))
  (define-key emacs-lisp-mode-map "\C-c\C-c" (lambda ()
                                               (interactive)
                                               (insert "(debug)")))
  )