(defun bartuer-clearcase-load ()
  "for load clearcase"
  (interactive)
  (if (require 'clearcase nil t)
      (let ((map clearcase-prefix-map))
        (define-key map "\C-o" 'clearcase-checkout-current-buffer)
        (define-key map "\C-i" 'clearcase-checkin-current-buffer)
        (define-key map "b" 'clearcase-gui-vtree-browser-current-buffer)
        (define-key map "p" 'clearcase-gui-diff-pred-current-buffer)
        (define-key map "=" 'clearcase-gui-diff-branch-base-current-buffer)
        (define-key map "n" 'clearcase-gui-diff-named-version-current-buffer)
        (define-key map "P" 'clearcase-ediff-pred-current-buffer)
        (define-key map "+" 'clearcase-ediff-branch-base-current-buffer)
        (define-key map "d" 'clearcase-describe-current-buffer)
        (define-key map "a" 'clearcase-annotate-current-buffer)
        (define-key map "t" 'clearcase-browse-vtree-current-buffer)
        (define-key map "h" 'clearcase-list-history-current-buffer)
        (define-key map "v" 'clearcase-next-action-current-buffer))))