(file-cache-add-directory-list (list
                                "~"
                                "~/etc/el"
                                "~/etc/el/kb"
                                "~/etc/el/vendor/fsharp-mode"
                                "~/local/share/doc/fsharp/project"
                                "~/org"
                                "~/org/corp_note"
                                "~/local/src/emacs_win_port"
                                "~/dev/osfclient/web/jscript"
                                "~/dev/biserver/EwaJs"
                                "~/dev/biserver/EwaJs/Agave"
                                "~/dev/biserver/EwaJs/Features/ChartInsert"
                                "~/dev/biserver/EwaJs/Features/WebExtension"
                                ))