(file-cache-add-directory-list (list
                                "~/local/src/tone"
                                "~/local/src/tone/js"
                                "~/local/src/tone/css"
                                "~/local/src/tone/doc/sample"
                                "~/local/src/widget/video-controller"
                                "~/local/src/pass"
                                "~/Movies/kids"
                                "~/local/src/bew"
                                "~/local/src/bew/src"
                                "~/local/src/bew/lib/libeio"
                                "~/local/src/bew/lib/libev"
                                "~/local/src/xrb"
                                "~/local/src/cells/"
                                "~/local/src/yogi"
                                "~/local/src/encoder/ffmpeg/doc"
                                "~/local/src/color_page"
                                ))
