(file-cache-add-directory-list (list
                                "~"
                                "~/org"
                                "~/etc/el"
                                "~/org"
                                "~/etc/el/vendor/swift-mode" 
                                "~/local/src/swift"
                                "~/local/src/swift/avcapture_osx.playground" 
                                "~/local/src/swift/avcapture_osx.playground/playground.xcworkspace" 
                                "~/local/src/swift/avcapture_osx.playground/playground.xcworkspace/xcuserdata" 
                                "~/local/src/swift/avcapture_osx.playground/playground.xcworkspace/xcuserdata/bartuer.xcuserdatad" 
                                "~/local/src/swift/GuidedTour.playground" 
                                "~/local/src/swift/GuidedTour.playground/Pages" 
                                "~/local/src/swift/GuidedTour.playground/Pages/Control Flow.xcplaygroundpage" 
                                "~/local/src/swift/GuidedTour.playground/Pages/Enumerations and Structures.xcplaygroundpage" 
                                "~/local/src/swift/GuidedTour.playground/Pages/Functions and Closures.xcplaygroundpage" 
                                "~/local/src/swift/GuidedTour.playground/Pages/Generics.xcplaygroundpage" 
                                "~/local/src/swift/GuidedTour.playground/Pages/License.xcplaygroundpage" 
                                "~/local/src/swift/GuidedTour.playground/Pages/Objects and Classes.xcplaygroundpage" 
                                "~/local/src/swift/GuidedTour.playground/Pages/Protocols and Extensions.xcplaygroundpage" 
                                "~/local/src/swift/GuidedTour.playground/Pages/Simple Values.xcplaygroundpage" 
                                "~/local/src/swift/GuidedTour.playground/playground.xcworkspace" 
                                "~/local/src/swift/GuidedTour.playground/playground.xcworkspace/xcuserdata" 
                                "~/local/src/swift/GuidedTour.playground/playground.xcworkspace/xcuserdata/bartuer.xcuserdatad" 
                                "~/local/src/swift/Swift Standard Library.playground" 
                                "~/local/src/swift/Swift Standard Library.playground/Pages" 
                                "~/local/src/swift/Swift Standard Library.playground/Pages/Customizing Textual Representations.xcplaygroundpage" 
                                "~/local/src/swift/Swift Standard Library.playground/Pages/Customizing Textual Representations.xcplaygroundpage/Sources" 
                                "~/local/src/swift/Swift Standard Library.playground/Pages/Indexing and Slicing Strings.xcplaygroundpage" 
                                "~/local/src/swift/Swift Standard Library.playground/Pages/Indexing and Slicing Strings.xcplaygroundpage/Sources" 
                                "~/local/src/swift/Swift Standard Library.playground/Pages/License.xcplaygroundpage" 
                                "~/local/src/swift/Swift Standard Library.playground/Pages/Processing Sequences and Collections.xcplaygroundpage" 
                                "~/local/src/swift/Swift Standard Library.playground/Pages/Revision History.xcplaygroundpage" 
                                "~/local/src/swift/Swift Standard Library.playground/Pages/Sequences and Collections.xcplaygroundpage" 
                                "~/local/src/swift/Swift Standard Library.playground/Pages/Slicing Collections.xcplaygroundpage" 
                                "~/local/src/swift/Swift Standard Library.playground/Pages/Slicing Collections.xcplaygroundpage/Sources" 
                                "~/local/src/swift/Swift Standard Library.playground/Pages/Table of Contents.xcplaygroundpage" 
                                "~/local/src/swift/Swift Standard Library.playground/Pages/Text.xcplaygroundpage" 
                                "~/local/src/swift/Swift Standard Library.playground/Pages/Understanding Sequence and Collection Protocols.xcplaygroundpage" 
                                "~/local/src/swift/Swift Standard Library.playground/Pages/Understanding Sequence and Collection Protocols.xcplaygroundpage/Resources" 
                                "~/local/src/swift/Swift Standard Library.playground/Pages/Understanding Sequence and Collection Protocols.xcplaygroundpage/Sources" 
                                "~/local/src/swift/Swift Standard Library.playground/Pages/Understanding Value Semantics.xcplaygroundpage" 
                                "~/local/src/swift/Swift Standard Library.playground/playground.xcworkspace" 
                                "~/local/src/swift/Swift Standard Library.playground/playground.xcworkspace/xcuserdata" 
                                "~/local/src/swift/Swift Standard Library.playground/playground.xcworkspace/xcuserdata/bartuer.xcuserdatad" 
                                "~/local/src/swift/Swift Standard Library.playground/Sources"
                                "~/local/src/selfie/jxcore/deps/leveldown-mobile"
                                "~/local/src/selfie/jxcore-addon"
                                ))
(eval-after-load
       "filecache"
       '(progn
          (message "Loading file cache...")
          (file-cache-add-directory-using-find
           "~/local/src/swift")
))