(eval-when-compile    (require 'color-theme))
(defun bartuer-main-theme ()
  "Color theme by bartuer, created 2011-01-21."
  (interactive)
  (color-theme-install
   '(bartuer-main-theme
     ((background-color . "unspecified-bg")
      (background-mode . dark)
      (foreground-color . "yellow"))
     ((anything-show-completion-face . highlight)
      (compilation-message-face . underline)
      (gnus-mouse-face . highlight)
      (gnus-summary-selected-face . gnus-summary-selected)
      (goto-address-mail-face . italic)
      (goto-address-mail-mouse-face . secondary-selection)
      (goto-address-url-face . link)
      (goto-address-url-mouse-face . highlight)
      (ibuffer-deletion-face . font-lock-type-face)
      (ibuffer-filter-group-name-face . bold)
      (ibuffer-marked-face . font-lock-warning-face)
      (ibuffer-title-face . font-lock-type-face)
      (ispell-highlight-face . flyspell-incorrect)
      (list-matching-lines-buffer-name-face . underline)
      (list-matching-lines-face . match)
      (org-goto-interface . outline)
      (org-remember-interactive-interface . refile)
      (tags-tag-face . default)
      (view-highlight-face . highlight)
      (widget-mouse-face . highlight))
     (default ((t (:stipple nil :background "unspecified-bg" :foreground "yellow" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 1 :width normal :foundry "default" :family "default"))))
     (anything-bookmarks-su-face ((t (:foreground "red"))))
     (anything-dir-heading ((t (:background "Pink" :foreground "Blue"))))
     (anything-dir-priv ((t (:background "LightGray" :foreground "DarkRed"))))
     (anything-file-name ((t (:foreground "Blue"))))
     (anything-gentoo-match-face ((t (:foreground "red"))))
     (anything-header ((t (:underline t))))
     (anything-isearch-match ((t (:background "Yellow"))))
     (anything-match ((t (:foreground "white" :background "blue"))))
     (anything-overlay-line-face ((t (:background "IndianRed4" :underline t))))
     (anything-visible-mark ((t (:background "green" :foreground "black"))))
     (anything-w3m-bookmarks-face ((t (:foreground "cyan1" :underline t))))
     (bold ((t (:bold t :weight bold))))
     (bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (bookmark-menu-heading ((t (:foreground "green"))))
     (border ((t (nil))))
     (buffer-menu-buffer ((t (:bold t :weight bold))))
     (button ((t (:foreground "cyan" :underline t))))
     (calendar-today ((t (:underline t))))
     (change-log-acknowledgement ((t (:foreground "green"))))
     (change-log-conditionals ((t (:weight light :foreground "white"))))
     (change-log-date ((t (:foreground "green"))))
     (change-log-email ((t (:weight light :foreground "white"))))
     (change-log-file ((t (:bold t :weight bold :foreground "blue"))))
     (change-log-function ((t (:weight light :foreground "white"))))
     (change-log-list ((t (:bold t :weight bold :foreground "cyan"))))
     (change-log-name ((t (:foreground "magenta"))))
     (comint-highlight-input ((t (:bold t :weight bold))))
     (comint-highlight-prompt ((t (:foreground "cyan"))))
     (compilation-column-number ((t (:foreground "green"))))
     (compilation-error ((t (:foreground "red"))))
     (compilation-info ((t (:bold t :foreground "green" :weight bold))))
     (compilation-line-number ((t (:weight light :foreground "white"))))
     (compilation-warning ((t (:bold t :foreground "cyan" :weight bold))))
     (completions-common-part ((t (nil))))
     (completions-first-difference ((t (nil))))
     (css-property ((t (:bold t :weight bold :foreground "cyan"))))
     (css-selector ((t (:bold t :weight bold :foreground "blue"))))
     (cursor ((t (:foreground "white"))))
     (custom-button ((t (nil))))
     (custom-button-mouse ((t (nil))))
     (custom-button-pressed ((t (nil))))
     (custom-button-pressed-unraised ((t (:underline t :foreground "violet"))))
     (custom-button-unraised ((t (:underline t))))
     (custom-changed ((t (:background "blue" :foreground "white"))))
     (custom-comment ((t (:background "yellow3" :foreground "black"))))
     (custom-comment-tag ((t (nil))))
     (custom-documentation ((t (nil))))
     (custom-face-tag ((t (:bold t :weight bold :foreground "light blue"))))
     (custom-group-tag ((t (:bold t :family "Sans Serif" :foreground "light blue" :weight bold :height 1.2))))
     (custom-group-tag-1 ((t (:bold t :family "Sans Serif" :foreground "pink" :weight bold :height 1.2))))
     (custom-invalid ((t (:background "red1" :foreground "yellow1"))))
     (custom-link ((t (nil))))
     (custom-modified ((t (:background "blue" :foreground "white"))))
     (custom-rogue ((t (:background "black" :foreground "pink"))))
     (custom-saved ((t (:underline t))))
     (custom-set ((t (:background "white" :foreground "blue"))))
     (custom-state ((t (:foreground "lime green"))))
     (custom-themed ((t (:background "blue" :foreground "white"))))
     (custom-variable-button ((t (:bold t :underline t :weight bold))))
     (custom-variable-tag ((t (:bold t :foreground "light blue" :weight bold))))
     (custom-visibility ((t (:height 0.8))))
     (derl-trace-input-face ((t (:foreground "green"))))
     (derl-trace-output-face ((t (:foreground "green"))))
     (diary ((t (:foreground "yellow"))))
     (diff-added ((t (:italic t :bold t :weight bold :slant italic :foreground "yellow"))))
     (diff-changed ((t (:italic t :bold t :foreground "yellow" :slant italic :weight bold))))
     (diff-context ((t (nil))))
     (diff-file-header ((t (:bold t :foreground "cyan" :weight bold))))
     (diff-function ((t (:bold t :weight bold :foreground "green"))))
     (diff-header ((t (:bold t :foreground "green" :weight bold))))
     (diff-hunk-header ((t (:bold t :weight bold :foreground "green"))))
     (diff-index ((t (:bold t :weight bold :foreground "cyan"))))
     (diff-indicator-added ((t (:italic t :bold t :foreground "yellow" :slant italic :weight bold))))
     (diff-indicator-changed ((t (:italic t :bold t :weight bold :slant italic :foreground "yellow"))))
     (diff-indicator-removed ((t (:italic t :bold t :foreground "yellow" :slant italic :weight bold))))
     (diff-nonexistent ((t (:bold t :weight bold :foreground "cyan"))))
     (diff-refine-change ((t (:background "green"))))
     (diff-removed ((t (:italic t :bold t :weight bold :slant italic :foreground "yellow"))))
     (dired-directory ((t (:bold t :weight bold :foreground "blue"))))
     (dired-flagged ((t (:foreground "red"))))
     (dired-header ((t (:foreground "green"))))
     (dired-ignored ((t (:foreground "yellow"))))
     (dired-mark ((t (:foreground "magenta"))))
     (dired-marked ((t (:foreground "red"))))
     (dired-perm-write ((t (:foreground "red1"))))
     (dired-symlink ((t (:bold t :weight bold :foreground "cyan"))))
     (dired-warning ((t (:foreground "red"))))
     (dropdown-list-face ((t (:family "default" :foundry "default" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :stipple nil :background "lightyellow" :foreground "black" :height 1))))
     (dropdown-list-selection-face ((t (:foreground "black" :stipple nil :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "default" :family "default" :background "purple" :height 1))))
     (edb-breakpoint-face ((t (:background "red" :foreground "black"))))
     (edb-breakpoint-stale-face ((t (:background "yellow" :foreground "black"))))
     (eldoc-highlight-function-argument ((t (:bold t :weight bold))))
     (erb-comment-delim-face ((t (:foreground "lightgreen"))))
     (erb-comment-face ((t (:foreground "lightgreen"))))
     (erb-delim-face ((t (:italic t :bold t :foreground "blue" :slant italic :weight bold))))
     (erb-exec-delim-face ((t (:italic t :bold t :slant italic :foreground "blue" :weight bold))))
     (erb-exec-face ((t (nil))))
     (erb-face ((t (nil))))
     (erb-out-delim-face ((t (:background "#383838" :foreground "#aaffff"))))
     (erb-out-face ((t (nil))))
     (erl-fdoc-name-face ((t (:bold t :weight bold))))
     (escape-glyph ((t (:foreground "cyan"))))
     (ffap ((t (:foreground "black" :background "green"))))
     (file-name-shadow ((t (:foreground "yellow"))))
     (fixed-pitch ((t (:family "Monospace"))))
     (flymake-errline ((t (:foreground "red"))))
     (flymake-pos ((t (:background "yellow" :foreground "red"))))
     (flymake-warnline ((t (:foreground "pink"))))
     (flyspell-duplicate ((t (:underline t))))
     (flyspell-duplicate-face ((t (:underline t))))
     (flyspell-incorrect ((t (:underline "red"))))
     (flyspell-incorrect-face ((t (:underline "red"))))
     (font-lock-builtin-face ((t (:bold t :foreground "blue" :weight bold))))
     (font-lock-comment-delimiter-face ((t (:foreground "red1"))))
     (font-lock-comment-face ((t (:foreground "green"))))
     (font-lock-constant-face ((t (:foreground "magenta"))))
     (font-lock-doc-face ((t (:foreground "green"))))
     (font-lock-function-name-face ((t (:bold t :foreground "blue" :weight bold))))
     (font-lock-keyword-face ((t (:bold t :foreground "cyan" :weight bold))))
     (font-lock-negation-char-face ((t (nil))))
     (font-lock-preprocessor-face ((t (:bold t :weight bold :foreground "blue"))))
     (font-lock-regexp-grouping-backslash ((t (:bold t :weight bold))))
     (font-lock-regexp-grouping-construct ((t (:bold t :weight bold))))
     (font-lock-string-face ((t (:foreground "green"))))
     (font-lock-type-face ((t (:foreground "green"))))
     (font-lock-variable-name-face ((t (:foreground "white" :weight light))))
     (font-lock-warning-face ((t (:foreground "red"))))
     (fringe ((t (:background "grey10"))))
     (gnus-group-mail-1 ((t (:bold t :foreground "#e1ffe1" :weight bold))))
     (gnus-group-mail-1-empty ((t (:foreground "#e1ffe1"))))
     (gnus-group-mail-2 ((t (:bold t :foreground "DarkSeaGreen1" :weight bold))))
     (gnus-group-mail-2-empty ((t (:foreground "DarkSeaGreen1"))))
     (gnus-group-mail-3 ((t (:bold t :foreground "aquamarine1" :weight bold))))
     (gnus-group-mail-3-empty ((t (:foreground "aquamarine1"))))
     (gnus-group-mail-low ((t (:bold t :foreground "aquamarine2" :weight bold))))
     (gnus-group-mail-low-empty ((t (:foreground "aquamarine2"))))
     (gnus-group-news-1 ((t (:bold t :foreground "PaleTurquoise" :weight bold))))
     (gnus-group-news-1-empty ((t (:foreground "PaleTurquoise"))))
     (gnus-group-news-2 ((t (:bold t :foreground "turquoise" :weight bold))))
     (gnus-group-news-2-empty ((t (:foreground "turquoise"))))
     (gnus-group-news-3 ((t (:bold t :weight bold))))
     (gnus-group-news-3-empty ((t (nil))))
     (gnus-group-news-4 ((t (:bold t :weight bold))))
     (gnus-group-news-4-empty ((t (nil))))
     (gnus-group-news-5 ((t (:bold t :weight bold))))
     (gnus-group-news-5-empty ((t (nil))))
     (gnus-group-news-6 ((t (:bold t :weight bold))))
     (gnus-group-news-6-empty ((t (nil))))
     (gnus-group-news-low ((t (:bold t :foreground "DarkTurquoise" :weight bold))))
     (gnus-group-news-low-empty ((t (:foreground "DarkTurquoise"))))
     (gnus-splash ((t (:foreground "#cccccc"))))
     (gnus-summary-cancelled ((t (:background "black" :foreground "yellow"))))
     (gnus-summary-high-ancient ((t (:bold t :foreground "SkyBlue" :weight bold))))
     (gnus-summary-high-read ((t (:bold t :foreground "PaleGreen" :weight bold))))
     (gnus-summary-high-ticked ((t (:bold t :foreground "pink" :weight bold))))
     (gnus-summary-high-undownloaded ((t (:bold t :foreground "LightGray" :weight bold))))
     (gnus-summary-high-unread ((t (:bold t :weight bold))))
     (gnus-summary-low-ancient ((t (:italic t :foreground "SkyBlue" :slant italic))))
     (gnus-summary-low-read ((t (:italic t :foreground "PaleGreen" :slant italic))))
     (gnus-summary-low-ticked ((t (:italic t :foreground "pink" :slant italic))))
     (gnus-summary-low-undownloaded ((t (:italic t :foreground "LightGray" :slant italic :weight normal))))
     (gnus-summary-low-unread ((t (:italic t :slant italic))))
     (gnus-summary-normal-ancient ((t (:foreground "SkyBlue"))))
     (gnus-summary-normal-read ((t (:foreground "PaleGreen"))))
     (gnus-summary-normal-ticked ((t (:foreground "pink"))))
     (gnus-summary-normal-undownloaded ((t (:foreground "LightGray" :weight normal))))
     (gnus-summary-normal-unread ((t (nil))))
     (gnus-summary-selected ((t (:underline t))))
     (header-line ((t (:underline t))))
     (help-argument-name ((t (nil))))
     (highlight ((t (:background "green" :foreground "black"))))
     (holiday ((t (:background "chocolate4"))))
     (icicle-Completions-instruction-1 ((t (:foreground "#AC4AAC4A0000"))))
     (icicle-Completions-instruction-2 ((t (:foreground "#0000D53CD53C"))))
     (icicle-candidate-part ((t (:foreground "red"))))
     (icicle-common-match-highlight-Completions ((t (:foreground "#2017A71F2017"))))
     (icicle-complete-input ((t (:foreground "green"))))
     (icicle-completion ((t (:foreground "#0000D53CD53C"))))
     (icicle-current-candidate-highlight ((t (:foreground "green"))))
     (icicle-historical-candidate ((t (:foreground "#DBD599DF0000"))))
     (icicle-input-completion-fail ((t (:background "#22225F5F2222"))))
     (icicle-input-completion-fail-lax ((t (:background "#00005E3B5A8D"))))
     (icicle-match-highlight-Completions ((t (:foreground "#1F1FA21CA21C"))))
     (icicle-match-highlight-minibuffer ((t (:underline t))))
     (icicle-multi-command-completion ((t (:background "#8B3500007533" :foreground "#0000D53CD53C"))))
     (icicle-mustmatch-completion ((t (nil))))
     (icicle-proxy-candidate ((t (:background "#316B22970000"))))
     (icicle-saved-candidate ((t (:background "gray20"))))
     (icicle-search-context-level-1 ((t (:background "#071F473A0000"))))
     (icicle-search-context-level-2 ((t (:background "#507400002839"))))
     (icicle-search-context-level-3 ((t (:background "#4517305D0000"))))
     (icicle-search-context-level-4 ((t (nil))))
     (icicle-search-context-level-5 ((t (:background "#04602BC00000"))))
     (icicle-search-context-level-6 ((t (:background "#32F200001979"))))
     (icicle-search-context-level-7 ((t (:background "#316B22970000"))))
     (icicle-search-context-level-8 ((t (nil))))
     (icicle-search-current-input ((t (:background "#7F0D00007F0D" :foreground "White"))))
     (icicle-search-main-regexp-current ((t (:background "#00004AA652F1"))))
     (icicle-search-main-regexp-others ((t (:background "#348608690000"))))
     (icicle-special-candidate ((t (nil))))
     (icicle-whitespace-highlight ((t (:background "#000093F402A2"))))
     (ido-first-match ((t (:bold t :weight bold))))
     (ido-incomplete-regexp ((t (:foreground "red"))))
     (ido-indicator ((t (:background "red" :foreground "yellow" :width condensed))))
     (ido-only-match ((t (:foreground "ForestGreen"))))
     (ido-subdir ((t (:foreground "red"))))
     (info-header-node ((t (:italic t :bold t :weight bold :slant italic :foreground "white"))))
     (info-header-xref ((t (nil))))
     (info-menu-header ((t (:bold t :underline t :weight bold))))
     (info-menu-star ((t (:foreground "red1"))))
     (info-node ((t (:italic t :bold t :foreground "white" :slant italic :weight bold))))
     (info-title-1 ((t (:bold t :foreground "yellow" :weight bold))))
     (info-title-2 ((t (:bold t :foreground "lightblue" :weight bold))))
     (info-title-3 ((t (:bold t :weight bold))))
     (info-title-4 ((t (:bold t :weight bold))))
     (info-xref ((t (nil))))
     (info-xref-visited ((t (:foreground "violet"))))
     (isearch ((t (:background "magenta4" :foreground "cyan1"))))
     (isearch-fail ((t (:background "red"))))
     (italic ((t (:underline t))))
     (lazy-highlight ((t (:background "turquoise3"))))
     (link ((t (nil))))
     (link-visited ((t (:foreground "violet"))))
     (magit-branch ((t (:bold t :weight bold))))
     (magit-diff-add ((t (:foreground "white"))))
     (magit-diff-del ((t (:foreground "OrangeRed"))))
     (magit-diff-file-header ((t (nil))))
     (magit-diff-hunk-header ((t (:italic t :slant italic))))
     (magit-diff-none ((t (nil))))
     (magit-header ((t (nil))))
     (magit-item-highlight ((t (:foreground "green"))))
     (magit-log-head-label ((t (:background "DarkGreen"))))
     (magit-log-tag-label ((t (:background "blue"))))
     (magit-section-title ((t (:bold t :foreground "red" :weight bold))))
     (match ((t (:background "blue" :foreground "white"))))
     (menu ((t (nil))))
     (message-cited-text ((t (:foreground "LightPink1"))))
     (message-header-cc ((t (:bold t :foreground "chartreuse1" :weight bold))))
     (message-header-name ((t (:foreground "green"))))
     (message-header-newsgroups ((t (:italic t :bold t :foreground "yellow" :slant italic :weight bold))))
     (message-header-other ((t (:foreground "VioletRed1"))))
     (message-header-subject ((t (:foreground "OliveDrab1"))))
     (message-header-to ((t (:bold t :foreground "DarkOliveGreen1" :weight bold))))
     (message-header-xheader ((t (:foreground "DeepSkyBlue1"))))
     (message-mml ((t (:foreground "MediumSpringGreen"))))
     (message-separator ((t (:foreground "LightSkyBlue1"))))
     (minibuffer-prompt ((t (:foreground "cyan"))))
     (mode-line ((t (nil))))
     (mode-line-buffer-id ((t (:bold t :background "yellow" :foreground "blue" :weight bold))))
     (mode-line-emphasis ((t (:bold t :weight bold))))
     (mode-line-highlight ((t (:foreground "black" :background "green"))))
     (mode-line-inactive ((t (nil))))
     (mouse ((t (nil))))
     (next-error ((t (:foreground "white" :background "blue"))))
     (nobreak-space ((t (:background "magenta"))))
     (org-agenda-clocking ((t (:foreground "black" :background "cyan"))))
     (org-agenda-column-dateline ((t (:family "default" :weight normal :slant normal :underline nil :strike-through nil :foreground "cyan" :background "black" :height 1))))
     (org-agenda-date ((t (:bold t :weight bold :foreground "cyan"))))
     (org-agenda-date-today ((t (:italic t :bold t :foreground "cyan" :slant italic :weight bold))))
     (org-agenda-date-weekend ((t (:bold t :foreground "cyan" :weight bold))))
     (org-agenda-diary ((t (:family "default" :foundry "default" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "yellow" :background "unspecified-bg" :stipple nil :height 1))))
     (org-agenda-dimmed-todo-face ((t (:foreground "grey50"))))
     (org-agenda-done ((t (:foreground "green"))))
     (org-agenda-restriction-lock ((t (:background "cyan" :foreground "black"))))
     (org-agenda-structure ((t (:bold t :foreground "cyan" :weight bold))))
     (org-archived ((t (:foreground "yellow"))))
     (org-block ((t (:foreground "yellow"))))
     (org-checkbox ((t (:bold t :weight bold))))
     (org-checkbox-statistics-done ((t (:foreground "green"))))
     (org-checkbox-statistics-todo ((t (:bold t :weight bold :foreground "red"))))
     (org-clock-overlay ((t (:background "cyan" :foreground "black"))))
     (org-code ((t (:foreground "yellow"))))
     (org-column ((t (:background "black" :foreground "cyan" :strike-through nil :underline nil :slant normal :weight normal :height 1 :family "default"))))
     (org-column-title ((t (:bold t :background "cyan" :foreground "black" :underline t :weight bold))))
     (org-date ((t (:foreground "Cyan" :underline t))))
     (org-document-info ((t (:foreground "pale turquoise"))))
     (org-document-info-keyword ((t (:foreground "yellow"))))
     (org-document-title ((t (:bold t :foreground "pale turquoise" :weight bold :height 1.44))))
     (org-done ((t (:foreground "green"))))
     (org-drawer ((t (:bold t :foreground "cyan" :weight bold))))
     (org-ellipsis ((t (:foreground "LightGoldenrod" :underline t))))
     (org-footnote ((t (:foreground "Cyan" :underline t))))
     (org-formula ((t (:foreground "red"))))
     (org-headline-done ((t (nil))))
     (org-hide ((t (:foreground "black"))))
     (org-latex-and-export-specials ((t (:foreground "burlywood"))))
     (org-level-1 ((t (:foreground "cyan"))))
     (org-level-2 ((t (:foreground "white" :weight light))))
     (org-level-3 ((t (:bold t :foreground "cyan" :weight bold))))
     (org-level-4 ((t (:foreground "green"))))
     (org-level-5 ((t (:foreground "green"))))
     (org-level-6 ((t (:foreground "magenta"))))
     (org-level-7 ((t (:foreground "cyan"))))
     (org-level-8 ((t (:foreground "green"))))
     (org-link ((t (:foreground "cyan" :underline t))))
     (org-meta-line ((t (:foreground "green"))))
     (org-mode-line-clock ((t (nil))))
     (org-mode-line-clock-overrun ((t (:foreground "red"))))
     (org-property-value ((t (nil))))
     (org-quote ((t (:foreground "yellow"))))
     (org-scheduled ((t (:foreground "green"))))
     (org-scheduled-previously ((t (:bold t :foreground "red" :weight bold))))
     (org-scheduled-today ((t (:foreground "green"))))
     (org-sexp-date ((t (:foreground "Cyan"))))
     (org-special-keyword ((t (:italic t :slant italic))))
     (org-table ((t (nil))))
     (org-tag ((t (:bold t :weight bold))))
     (org-target ((t (:foreground "cyan" :underline t))))
     (org-time-grid ((t (:foreground "yellow" :weight light))))
     (org-todo ((t (:bold t :foreground "red" :weight bold))))
     (org-upcoming-deadline ((t (:bold t :foreground "red" :weight bold))))
     (org-verbatim ((t (:foreground "yellow"))))
     (org-verse ((t (:foreground "yellow"))))
     (org-warning ((t (:foreground "red"))))
     (outline-1 ((t (:bold t :weight bold :foreground "blue"))))
     (outline-2 ((t (:weight light :foreground "white"))))
     (outline-3 ((t (:bold t :weight bold :foreground "cyan"))))
     (outline-4 ((t (:foreground "green"))))
     (outline-5 ((t (:foreground "green"))))
     (outline-6 ((t (:foreground "magenta"))))
     (outline-7 ((t (:bold t :weight bold :foreground "blue"))))
     (outline-8 ((t (:foreground "green"))))
     (query-replace ((t (:foreground "cyan1" :background "magenta4"))))
     (region ((t (:background "blue" :foreground "white"))))
     (scroll-bar ((t (nil))))
     (secondary-selection ((t (:background "cyan" :foreground "black"))))
     (sgml-namespace ((t (:bold t :weight bold :foreground "blue"))))
     (shadow ((t (:foreground "yellow"))))
     (show-paren-match ((t (:background "steelblue3"))))
     (show-paren-mismatch ((t (:background "purple" :foreground "white"))))
     (speedbar-button-face ((t (:foreground "cyan" :underline t))))
     (speedbar-directory-face ((t (:foreground "light blue"))))
     (speedbar-file-face ((t (:foreground "cyan"))))
     (speedbar-highlight-face ((t (:background "sea green"))))
     (speedbar-selected-face ((t (:foreground "red" :underline t))))
     (speedbar-separator-face ((t (:background "blue" :foreground "white" :overline "gray"))))
     (speedbar-tag-face ((t (:foreground "yellow"))))
     (textile-acronym-face ((t (:foreground "cyan"))))
     (textile-alignments-face ((t (:foreground "cyan"))))
     (textile-blockquote-face ((t (:foreground "ivory4"))))
     (textile-citation-face ((t (:italic t :slant italic))))
     (textile-class-face ((t (:foreground "yellow green"))))
     (textile-code-face ((t (:foreground "ivory3"))))
     (textile-deleted-face ((t (:strike-through t))))
     (textile-emph-face ((t (:italic t :slant italic))))
     (textile-footnote-face ((t (:foreground "orange red"))))
     (textile-footnotemark-face ((t (:foreground "orange red"))))
     (textile-h1-face ((t (:bold t :weight bold :height 2.0))))
     (textile-h2-face ((t (:bold t :weight bold :height 1.75))))
     (textile-h3-face ((t (:bold t :weight bold :height 1.6))))
     (textile-h4-face ((t (:bold t :weight bold :height 1.35))))
     (textile-h5-face ((t (:bold t :weight bold :height 1.2))))
     (textile-h6-face ((t (:bold t :weight bold :height 1.0))))
     (textile-image-face ((t (:foreground "pink"))))
     (textile-inserted-face ((t (:underline t))))
     (textile-lang-face ((t (:foreground "sky blue"))))
     (textile-link-face ((t (:foreground "blue"))))
     (textile-ol-bullet-face ((t (:foreground "red"))))
     (textile-pre-face ((t (:foreground "green"))))
     (textile-span-face ((t (:foreground "pink"))))
     (textile-strong-face ((t (:bold t :weight bold))))
     (textile-style-face ((t (:foreground "sandy brown"))))
     (textile-subscript-face ((t (:height 0.8))))
     (textile-superscript-face ((t (:height 1.1))))
     (textile-table-face ((t (:foreground "red"))))
     (textile-ul-bullet-face ((t (:foreground "blue"))))
     (tool-bar ((t (:foreground "black" :box (:line-width 1 :style released-button)))))
     (trailing-whitespace ((t (:background "red1"))))
     (underline ((t (:underline t))))
     (variable-pitch ((t (:family "Sans Serif"))))
     (vertical-border ((t (nil))))
     (which-func ((t (:background "yellow" :foreground "blue"))))
     (widget-button ((t (:bold t :weight bold))))
     (widget-button-pressed ((t (:foreground "red"))))
     (widget-documentation ((t (:foreground "lime green"))))
     (widget-field ((t (:background "yellow3" :foreground "black"))))
     (widget-inactive ((t (:foreground "yellow"))))
     (widget-single-line-field ((t (:background "green3" :foreground "black"))))
     (yas/field-highlight-face ((t (:background "blue"))))
     (yas/mirror-highlight-face ((t (:background "blue")))))))
(add-to-list 'color-themes '(bartuer-main-theme  "Main" "Bartuer"))