(defun do-treesit-compile ()
     (interactive)
     ;; Pin grammars to last ABI ≤ 14 tags.
     ;; tree-sitter v0.22.6 (used by Emacs 30.1) supports ABI 13–14.
     ;; Grammars built from HEAD now emit ABI 15 (needs tree-sitter ≥ 0.24).
     (setq treesit-language-source-alist
           '((bash       "https://github.com/tree-sitter/tree-sitter-bash"       "v0.23.3")
             (cmake      "https://github.com/uyha/tree-sitter-cmake")
             (css        "https://github.com/tree-sitter/tree-sitter-css"        "v0.23.2")
             (elisp      "https://github.com/Wilfred/tree-sitter-elisp"          "1.5.0")
             (go         "https://github.com/tree-sitter/tree-sitter-go"         "v0.23.4")
             (html       "https://github.com/tree-sitter/tree-sitter-html")
             (javascript "https://github.com/tree-sitter/tree-sitter-javascript" "v0.23.1" "src")
             (json       "https://github.com/tree-sitter/tree-sitter-json")
             (make       "https://github.com/alemuller/tree-sitter-make")
             (markdown   "https://github.com/ikatyang/tree-sitter-markdown")
             (python     "https://github.com/tree-sitter/tree-sitter-python"     "v0.23.6")
             (toml       "https://github.com/tree-sitter/tree-sitter-toml")
             (tsx        "https://github.com/tree-sitter/tree-sitter-typescript" "v0.23.2" "tsx/src")
             (typescript "https://github.com/tree-sitter/tree-sitter-typescript" "v0.23.2" "typescript/src")
             (c          "https://github.com/tree-sitter/tree-sitter-c"          "v0.23.6")
             (cpp        "https://github.com/tree-sitter/tree-sitter-cpp"        "v0.23.4")
             (c-sharp    "https://github.com/tree-sitter/tree-sitter-c-sharp"    "v0.23.1")
             (rust       "https://github.com/tree-sitter/tree-sitter-rust"       "v0.23.3")
             (yaml       "https://github.com/ikatyang/tree-sitter-yaml"))))

     (mapc #'treesit-install-language-grammar (mapcar #'car treesit-language-source-alist))

     (treesit-language-available-p 'python)
     (treesit-language-available-p 'rust)
     (treesit-language-available-p 'cpp)
     (treesit-language-available-p 'c)
     (treesit-language-available-p 'c-sharp)
     (treesit-language-available-p 'javascript)
     (treesit-language-available-p 'typescript)
     (treesit-language-available-p 'go)
     )