(defun do-treesit-compile ()
     (interactive)
     (setq treesit-language-source-alist
           '((bash "https://github.com/tree-sitter/tree-sitter-bash")
             (cmake "https://github.com/uyha/tree-sitter-cmake")
             (css "https://github.com/tree-sitter/tree-sitter-css")
             (elisp "https://github.com/Wilfred/tree-sitter-elisp")
             (go "https://github.com/tree-sitter/tree-sitter-go")
             (html "https://github.com/tree-sitter/tree-sitter-html")
             (javascript "https://github.com/tree-sitter/tree-sitter-javascript" "master" "src")
             (json "https://github.com/tree-sitter/tree-sitter-json")
             (make "https://github.com/alemuller/tree-sitter-make")
             (markdown "https://github.com/ikatyang/tree-sitter-markdown")
             (python "https://github.com/tree-sitter/tree-sitter-python")
             (toml "https://github.com/tree-sitter/tree-sitter-toml")
             (tsx "https://github.com/tree-sitter/tree-sitter-typescript" "master" "tsx/src")
             (typescript "https://github.com/tree-sitter/tree-sitter-typescript" "master" "typescript/src")
             (c "https://github.com/tree-sitter/tree-sitter-c")
             (cpp "https://github.com/tree-sitter/tree-sitter-cpp")
             (c-sharp "https://github.com/tree-sitter/tree-sitter-c-sharp")
             (rust "https://github.com/tree-sitter/tree-sitter-rust")
             (yaml "https://github.com/ikatyang/tree-sitter-yaml")))

     (mapc #'treesit-install-language-grammar (mapcar #'car treesit-language-source-alist))

     (treesit-language-available-p 'python)
     (treesit-language-available-p 'rust)
     (treesit-language-available-p 'cpp)
     (treesit-language-available-p 'c)
     (treesit-language-available-p 'c-sharp)
     (treesit-language-available-p 'javascript)
     (treesit-language-available-p 'typescript)
     (treesit-language-available-p 'go)
     )