#!/usr/bin/env bash
# prg-typefind.sh — WRITE a type defect into the back-propagation channel,
# so a defect found at query time reaches the next extraction run.  NO LLM.
#
# WHY THIS EXISTS AND prg-join.sh DOES NOT ALREADY DO IT
# Plan 06 Phase 4 built a channel for JOIN defects: a finding written to
# `join-findings.jsonl` is read on the next run by jq/join-candidates.jq,
# which promotes or demotes the pair.  06/7.3 is the same channel for TYPE
# defects.  Today a type defect is found by the sql bench, BY HAND, after
# the DDL already exists, and nothing carries it back — the next scan of
# the same corpus re-derives the identical wrong column type.
#
# THE CHANNEL IS ALREADY BUILT; THIS IS THE MISSING WRITER.  Measured:
# join-findings.jsonl has exactly ONE reader repo-wide (prg-join.sh:299)
# and zero readers in src/.  So a finding written here is read by the same
# tool on the next run, and nothing in the C emitter has to change — which
# is the layer boundary 06/4.4's ruling settled ("emitsql does not read the
# ledger, it is generated by prg-join.sh parallel semantic schema
# discover").  This tool writes on the DISCOVERY side, where the ledger
# lives.
#
# THE OWNERSHIP SPLIT IS THE WHOLE POINT, and it is not ours to invent —
# fix.archive/sqlbench-finds-bin2md-defects.md already fixed it:
#     MODEL   a correct query EXISTS over the emitted db; the LLM missed it
#     BIN2MD  NO correct query exists, because the DDL destroyed the fact
# A type defect is BIN2MD-owned BY DEFINITION, which is exactly what makes
# it back-propagatable: there is something for the producer to do.  A MODEL
# defect is not written here at all — it has no producer-side remedy.
#
# :trap: NOT EVERY TEXT COLUMN IS A DEFECT, and a writer that cannot tell
# the difference drowns the channel in false positives.  06/7.3 measured
# the trap: 63 of 176 columns (36%) are 100% numeric-declared yet land
# TEXT, and that is DELIBERATE — src/emitsql.c:24 documents all-TEXT for
# the shapes where numeric storage would destroy bytes (a leading zero
# makes 0417 an identifier, not the number 417).  So this tool refuses to
# file a finding it cannot justify, and says which rule refused it.
#
# Subverbs:
#   scan DIR         report candidate type defects, one JSON row each; no write
#   file DIR         append the JUSTIFIED ones to DIR/join-findings.jsonl
#   show DIR         print the findings already in the channel
#
# Exit: 0 ok · 2 bad args / missing dep · 4 corpus absent · 5 nothing to read.
set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
JQD="$HERE/jq"

die() { printf 'prg-typefind: %s\n' "$1" >&2; exit "${2:-2}"; }
command -v jq >/dev/null || die "jq required"

usage() {
  cat >&2 <<'EOF'
prg-typefind.sh — write a TYPE defect into the back-propagation channel.

  prg-typefind.sh scan DIR      candidates, no write
  prg-typefind.sh file DIR      append justified findings to join-findings.jsonl
  prg-typefind.sh show DIR      what is already in the channel

A finding is {k:"finding", kind:"type", l:{file,sheet,hdr}, ...}.  It is
keyed on {file,sheet,hdr} and NEVER on column index -- an index is a
property of today's extraction and dies when a column is inserted
upstream.  Same keying as the join findings; same file.
EOF
  exit 2
}

# ---- the detector --------------------------------------------------------
# ONE rule, and it is the only one with a producer-side remedy: the cells
# DECLARE a type the DDL did not use.  `t` on a cell row is what the SOURCE
# DOCUMENT said (never re-sniffed -- see joincand.c's `t` doc), so a column
# whose cells are majority t=n while the column landed TEXT is a fact the
# DDL dropped.  Everything else is left alone on purpose.
scan() {
  local dir="$1"
  [ -d "$dir" ] || die "not a directory: $dir" 4
  local sql="$dir/insert.prg.sql"
  [ -s "$sql" ] || die "no insert.prg.sql in $dir (run --emit-ddl first)" 5
  local any=0
  for f in "$dir"/*.prg.jsonl; do
    [ -e "$f" ] || continue
    case "$(basename "$f")" in join.prg.jsonl) continue ;; esac
    any=1
    local base; base="$(basename "$f" .prg.jsonl)"
    # per (sheet,col): the declared-type histogram and the header text
    jq -s -c --arg file "$base" '
      [ .[] | select(.r != null and .c != null) ] as $cells
      | ($cells | map(select(.k=="cell")) ) as $cs
      | ( $cs | group_by([.s, .c])[]
          | { file: $file,
              sheet: (.[0].s // ""),
              col:   .[0].c,
              hdr:   ( [ .[] | select(.r == 1) | .v ][0] // "" ),
              n_all: ( [ .[] | select(.r > 1) ] | length ),
              n_num: ( [ .[] | select(.r > 1 and .t == "n") ] | length ),
              lz:    ( [ .[] | select(.r > 1 and (.v|type=="string")
                                      and (.v|test("^0[0-9]"))) ] | length ) } )
      | select(.n_all > 0 and .n_num > 0)
    ' "$f" 2>/dev/null
  done
  [ "$any" = 1 ] || die "no *.prg.jsonl sidecars in $dir" 5
}

# Join the per-column facts to the DDL's declared type and decide.
decide() {
  local dir="$1" sql="$dir/insert.prg.sql"
  # every column the DDL declared TEXT, as "table<TAB>column"
  awk '
    /^CREATE TABLE/ { t=$0; sub(/^CREATE TABLE "/,"",t); sub(/".*/,"",t); next }
    /^\);/          { t=""; next }
    t != "" && /^  "/ {
      line=$0; sub(/^  "/,"",line); name=line; sub(/".*/,"",name)
      rest=line; sub(/^[^"]*"[ \t]*/,"",rest)
      split(rest, a, /[ \t,]+/)
      if (a[1] == "TEXT") print name
    }' "$sql" | sort -u
}

emit_findings() {
  local dir="$1"
  local texts; texts="$(decide "$dir")"
  scan "$dir" | jq -c --arg texts "$texts" '
    # sql_name: the emitter normalises a header the same way everywhere --
    # lowercase, non-alnum -> _, collapse.  Recomputing it here is the only
    # way to line a stream column up with a DDL column.
    def sqlname: ascii_downcase | gsub("[^a-z0-9]+"; "_")
                 | sub("^_+"; "") | sub("_+$"; "");
    ($texts | split("\n") | map(select(length>0))) as $T
    | . as $c
    | ($c.hdr | sqlname) as $sn
    | select($sn != "" and ($T | index($sn)))
    | ($c.n_num / $c.n_all) as $ratio
    # THE REFUSALS, each named in the record so a reader can audit them.
    | if $c.lz > 0 then
        { skip: "leading-zero column: numeric storage would destroy bytes",
          file: $c.file, sheet: $c.sheet, hdr: $c.hdr }
      elif $ratio < 0.8 then
        { skip: "mixed column: \($c.n_num) of \($c.n_all) declare n",
          file: $c.file, sheet: $c.sheet, hdr: $c.hdr }
      else
        { k: "finding", kind: "type", by: "prg-typefind",
          owner: "bin2md",
          l: { file: $c.file, sheet: $c.sheet, hdr: $c.hdr },
          declared: "n", emitted: "TEXT",
          n_declared: $c.n_num, n_rows_observed: $c.n_all,
          why: "the source declares \($c.n_num) of \($c.n_all) data cells t=n; the DDL emitted TEXT, so no correct numeric query exists over this column" }
      end'
}

case "${1:-}" in
  scan) shift; [ $# -ge 1 ] || usage; emit_findings "$1" ;;
  file)
    shift; [ $# -ge 1 ] || usage
    dir="$1"; led="$dir/join-findings.jsonl"
    tmp="$(mktemp)"; emit_findings "$dir" | jq -c 'select(.k=="finding")' > "$tmp"
    n=$(grep -c . "$tmp" || true)
    if [ "${n:-0}" -eq 0 ]; then
      echo "prg-typefind: no justified type findings in $dir" >&2
      rm -f "$tmp"; exit 0
    fi
    # APPEND, never truncate: the channel already carries join findings and
    # this tool has no business rewriting them.
    cat "$tmp" >> "$led"; rm -f "$tmp"
    echo "prg-typefind: appended $n finding(s) to $led" >&2
    ;;
  show)
    shift; [ $# -ge 1 ] || usage
    led="$1/join-findings.jsonl"
    [ -s "$led" ] || die "no findings channel at $led" 5
    jq -c 'select(.k=="finding")' "$led"
    ;;
  *) usage ;;
esac
